alter table public.lessons add column if not exists external_url text;

with m as (
  insert into public.modules (title, description, sort_order)
  values ('AI in Medicine: Practical Applications for Healthcare',
    'Cloned from the NNCC Thinkific course (13 sections, 137 lessons). Videos, handouts and quizzes open on Thinkific. Full course: https://nncceducation.thinkific.com/courses/take/ai-placeholder-2',
    1)
  returning id
)
insert into public.lessons (module_id, title, content, external_url, sort_order)
select m.id, v.title, v.content, 'https://nncceducation.thinkific.com/courses/take/ai-placeholder-2', v.ord
from m, (values
(1, '▸ (Optional) Module 0: foundation, theory, and Application', 'Course section — open the full section on Thinkific.'),
(2, 'Data science and machine learning', 'Open this lesson on Thinkific to watch the video / view the material.'),
(3, 'AI toolkit navigating real time application in healthcare', 'Open this lesson on Thinkific to watch the video / view the material.'),
(4, 'Applied biostatistics for clinical reasoning how work around our dyscalculia', 'Open this lesson on Thinkific to watch the video / view the material.'),
(5, 'Holding Hands with the Machine', 'Open this lesson on Thinkific to watch the video / view the material.'),
(6, 'Welcome to Your new AI staff how to use LLM as your research and administrative assistant', 'Open this lesson on Thinkific to watch the video / view the material.'),
(7, 'Malpraxis-legal dilemmas and challenges with AI in healthcare By Dr. Abdullah Chahin', 'Open this lesson on Thinkific to watch the video / view the material.'),
(8, '▸ Module 1: AI in Medicine: Basic and general day to day applications', 'Course section — open the full section on Thinkific.'),
(9, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(10, 'Prompt Engineering Basics', 'Open this lesson on Thinkific to watch the video / view the material.'),
(11, 'Prompt Engineering Handout', 'Open this lesson on Thinkific to watch the video / view the material.'),
(12, 'ChatGPT', 'Open this lesson on Thinkific to watch the video / view the material.'),
(13, 'ChatGPT Handout', 'Open this lesson on Thinkific to watch the video / view the material.'),
(14, 'Grok', 'Open this lesson on Thinkific to watch the video / view the material.'),
(15, 'Grok Hand out', 'Open this lesson on Thinkific to watch the video / view the material.'),
(16, 'Gemini', 'Open this lesson on Thinkific to watch the video / view the material.'),
(17, 'Link for Gemini', 'Open this lesson on Thinkific to watch the video / view the material.'),
(18, 'Google Gemini Hand out', 'Open this lesson on Thinkific to watch the video / view the material.'),
(19, 'Claude AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(20, 'Claude AI handout', 'Open this lesson on Thinkific to watch the video / view the material.'),
(21, 'Module -1 Assignment', 'Open this lesson on Thinkific to watch the video / view the material.'),
(22, 'How to Submit the Module 1 Assignment - Step by Step Guide', 'Open this lesson on Thinkific to watch the video / view the material.'),
(23, 'AI Assignment Checker - Module 1', 'Open this lesson on Thinkific to watch the video / view the material.'),
(24, 'Upload Module -1 Assignment Files and Scoresheet here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(25, '▸ Module 2: Image & Video Generation, and AI Ethics', 'Course section — open the full section on Thinkific.'),
(26, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(27, 'Privacy and Ethics in AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(28, 'Creating AI-Generated Medical illustrations and Comics', 'Open this lesson on Thinkific to watch the video / view the material.'),
(29, 'Comic Prompt Generator - Major Upgrade', 'Open this lesson on Thinkific to watch the video / view the material.'),
(30, 'Links of AI Prompt Generator, Medical Illustrations & Comic Generator GPTs', 'Open this lesson on Thinkific to watch the video / view the material.'),
(31, 'Creating video using AI-1', 'Open this lesson on Thinkific to watch the video / view the material.'),
(32, 'Creating videos using AI -2', 'Open this lesson on Thinkific to watch the video / view the material.'),
(33, 'Creating videos using AI agents', 'Open this lesson on Thinkific to watch the video / view the material.'),
(34, 'Create Scientific Posters with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(35, 'Prompt to convert PDF Article to Scientific Poster in IMRAD', 'Open this lesson on Thinkific to watch the video / view the material.'),
(36, 'Module -2 Assignments', 'Open this lesson on Thinkific to watch the video / view the material.'),
(37, 'Upload Module -2 Assignment Files and Certificate here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(38, '▸ Module 3: AI Teaching & Learning Assistants', 'Course section — open the full section on Thinkific.'),
(39, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(40, '3.1 NotebookLM Basics', 'Open this lesson on Thinkific to watch the video / view the material.'),
(41, 'NotebookLM update', 'Open this lesson on Thinkific to watch the video / view the material.'),
(42, '3.2 Adding Sources to NotebookLM', 'Open this lesson on Thinkific to watch the video / view the material.'),
(43, '3.3 Podcast and Summary Report Generation', 'Open this lesson on Thinkific to watch the video / view the material.'),
(44, '3.4 Video and Mindmap Generation', 'Open this lesson on Thinkific to watch the video / view the material.'),
(45, '3.5 Creating Amazing Powerpoints from Textbooks', 'Open this lesson on Thinkific to watch the video / view the material.'),
(46, '3.6 Infographics Quiz and Flashcards', 'Open this lesson on Thinkific to watch the video / view the material.'),
(47, '3.7 Claude Artifacts and Gemini Canvas as Learning Companions', 'Open this lesson on Thinkific to watch the video / view the material.'),
(48, '3.8 CustomGPT and Gemini GEMS as Study Companions', 'Open this lesson on Thinkific to watch the video / view the material.'),
(49, 'Upload Module 3 assignment here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(50, 'Tutorial on Module 3 Assignment Submission', 'Open this lesson on Thinkific to watch the video / view the material.'),
(51, '▸ Module 4: AI for Academic Career Development', 'Course section — open the full section on Thinkific.'),
(52, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(53, '4.1 Blueprint of a Perfect CV', 'Open this lesson on Thinkific to watch the video / view the material.'),
(54, '4.2 CV Creation with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(55, '4.3 Designing the Visual Layouts of the CV', 'Open this lesson on Thinkific to watch the video / view the material.'),
(56, '4.4 Reference Letter Etiquettes and AI Disclosures', 'Open this lesson on Thinkific to watch the video / view the material.'),
(57, '4.5 Creating a stunning LinkedIn Profile from the CV', 'Open this lesson on Thinkific to watch the video / view the material.'),
(58, '4.6 Creating Portfolio Website from CV with QR Code', 'Open this lesson on Thinkific to watch the video / view the material.'),
(59, 'Download this Sample CV PDF for Assignment', 'Open this lesson on Thinkific to watch the video / view the material.'),
(60, 'Module 4 Assignment', 'Open this lesson on Thinkific to watch the video / view the material.'),
(61, '▸ Module 5: AI-Enhanced Literature Search', 'Course section — open the full section on Thinkific.'),
(62, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(63, '5.1 Consensus AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(64, '5.2 Perplexity AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(65, '5.3 Systematic Review planning with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(66, 'Systematic Review Prompts & Links', 'Open this lesson on Thinkific to watch the video / view the material.'),
(67, '5.4 Elicit AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(68, '5.5 Creating PRISMA Flow diagrams with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(69, 'Research Rabbit', 'Open this lesson on Thinkific to watch the video / view the material.'),
(70, 'Upload Module 5 assignment here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(71, '▸ Module 6: Research Proposal & Methodology', 'Course section — open the full section on Thinkific.'),
(72, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(73, '6.1 Brainstorming SMART Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(74, '6.2 Proposal Writing with ChatGPT and Gemini DeepResearch modes', 'Open this lesson on Thinkific to watch the video / view the material.'),
(75, '6.3 Proposal Writing with Grok, Perplexity and Consensus AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(76, 'Sample Size Calculation Tool', 'Open this lesson on Thinkific to watch the video / view the material.'),
(77, '6.4 DAG - Concept and Visualization with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(78, 'DAG Creation Prompt', 'Open this lesson on Thinkific to watch the video / view the material.'),
(79, 'Upload Module 6 assignment here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(80, '▸ Module 7: Statistics & Data Analysis', 'Course section — open the full section on Thinkific.'),
(81, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(82, '7.1 Fundamentals Concepts of Descriptive and Inferential Statistics', 'Open this lesson on Thinkific to watch the video / view the material.'),
(83, '7.2 Julius AI for Data Analysis', 'Open this lesson on Thinkific to watch the video / view the material.'),
(84, '7.3 Quadratic AI and Gemini CoPilot in Google Sheets', 'Open this lesson on Thinkific to watch the video / view the material.'),
(85, 'Prompts - AI Data Analysis using Julius', 'Open this lesson on Thinkific to watch the video / view the material.'),
(86, 'Data Analysis using Claude CoWork', 'Open this lesson on Thinkific to watch the video / view the material.'),
(87, 'Cowork Prompt Conductor GPT - The Power of Micro-Prompting in Medical Writing', 'Open this lesson on Thinkific to watch the video / view the material.'),
(88, 'Sample Size Calculation with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(89, 'Sample Prompts for Module 7', 'Open this lesson on Thinkific to watch the video / view the material.'),
(90, 'Sample Data Files', 'Open this lesson on Thinkific to watch the video / view the material.'),
(91, 'Upload Module 7 assignment here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(92, '▸ Module 8: Manuscript Writing & AI Governance', 'Course section — open the full section on Thinkific.'),
(93, 'Module Objectives', 'Open this lesson on Thinkific to watch the video / view the material.'),
(94, '8.1 Fundamentals of IMRAD Framework', 'Open this lesson on Thinkific to watch the video / view the material.'),
(95, '8.2 Manuscript Writing with PaperPal in IMRAD format', 'Open this lesson on Thinkific to watch the video / view the material.'),
(96, 'Coupon Codes for Paperpal', 'Open this lesson on Thinkific to watch the video / view the material.'),
(97, 'How to Add Custom Articles to Paperpal', 'Open this lesson on Thinkific to watch the video / view the material.'),
(98, '8.3 Zotero and its integration with AI tools', 'Open this lesson on Thinkific to watch the video / view the material.'),
(99, '8.4 Plagiarism Detection tools and Paraphrasing with AI', 'Open this lesson on Thinkific to watch the video / view the material.'),
(100, '8.5 AI Detection and Guidelines in Research', 'Open this lesson on Thinkific to watch the video / view the material.'),
(101, 'AI watermark removal prompt', 'Open this lesson on Thinkific to watch the video / view the material.'),
(102, 'AI Humanisers - Which is the best one in 2026', 'Open this lesson on Thinkific to watch the video / view the material.'),
(103, 'Upload Module 8 assignment here', 'Open this lesson on Thinkific to watch the video / view the material.'),
(104, '▸ Module 10: Miscellaneous', 'Course section — open the full section on Thinkific.'),
(105, 'How to create AI tools using a combo of Gemini and Google AI studio', 'Open this lesson on Thinkific to watch the video / view the material.'),
(106, 'Bulid your first AI app in AI studio', 'Open this lesson on Thinkific to watch the video / view the material.'),
(107, 'A step-by-step guide', 'Open this lesson on Thinkific to watch the video / view the material.'),
(108, 'A step by step infographic', 'Open this lesson on Thinkific to watch the video / view the material.'),
(109, 'Cloning your voice and adding it to PPT', 'Open this lesson on Thinkific to watch the video / view the material.'),
(110, '▸ Optional : AI Agentic use', 'Course section — open the full section on Thinkific.'),
(111, '1.1 Slides — Course Objectives & Orientation', 'Open this lesson on Thinkific to watch the video / view the material.'),
(112, '1.2 Video — AI Agents, Clearly Explained', 'Open this lesson on Thinkific to watch the video / view the material.'),
(113, '1.3 Assignment — Set Your Learning Goal', 'Open this lesson on Thinkific to watch the video / view the material.'),
(114, '1.4 Mini Quiz — Objectives & Orientation', 'Open this lesson on Thinkific to watch the video / view the material.'),
(115, '2.1 Slides — Agentic AI in 2026: The Shared Picture', 'Open this lesson on Thinkific to watch the video / view the material.'),
(116, '2.2 Video — Agentic AI Frameworks Explained', 'Open this lesson on Thinkific to watch the video / view the material.'),
(117, '2.3 Assignment — Apply the Verifiability Lens', 'Open this lesson on Thinkific to watch the video / view the material.'),
(118, '2.4 Mini Quiz — The Shared Picture', 'Open this lesson on Thinkific to watch the video / view the material.'),
(119, '3.1 Slides — How to Drive Any Agent Well', 'Open this lesson on Thinkific to watch the video / view the material.'),
(120, '3.2 Video — How to Use Agentic AI (Prompting in Action)', 'Open this lesson on Thinkific to watch the video / view the material.'),
(121, '3.3 Assignment — Rewrite a Weak Prompt', 'Open this lesson on Thinkific to watch the video / view the material.'),
(122, '3.4 Mini Quiz — Driving Agents Well', 'Open this lesson on Thinkific to watch the video / view the material.'),
(123, '4.1 Slides — Claude (Anthropic)', 'Open this lesson on Thinkific to watch the video / view the material.'),
(124, '4.2 Video — Master Claude in 20 Minutes (Beginner Guide)', 'Open this lesson on Thinkific to watch the video / view the material.'),
(125, '4.3 Assignment — Plan a Claude Task', 'Open this lesson on Thinkific to watch the video / view the material.'),
(126, '4.4 Mini Quiz — Claude', 'Open this lesson on Thinkific to watch the video / view the material.'),
(127, '5.1 Slides — Gemini (Google)', 'Open this lesson on Thinkific to watch the video / view the material.'),
(128, '5.2 Video — Master Gemini: Workspace, Deep Research & Gems', 'Open this lesson on Thinkific to watch the video / view the material.'),
(129, '5.3 Assignment — Use the Large Context Window', 'Open this lesson on Thinkific to watch the video / view the material.'),
(130, '5.4 Mini Quiz — Gemini', 'Open this lesson on Thinkific to watch the video / view the material.'),
(131, '6.1 Slides — Microsoft Copilot', 'Open this lesson on Thinkific to watch the video / view the material.'),
(132, '6.2 Video — Build and Use Agents in Microsoft 365 Copilot', 'Open this lesson on Thinkific to watch the video / view the material.'),
(133, '6.3 Assignment — Match the Surface to the Task', 'Open this lesson on Thinkific to watch the video / view the material.'),
(134, '6.4 Mini Quiz — Microsoft Copilot', 'Open this lesson on Thinkific to watch the video / view the material.'),
(135, '7.1 Slides — Manus', 'Open this lesson on Thinkific to watch the video / view the material.'),
(136, '7.2 Video — Manus AI Explained: Setup & Use Cases', 'Open this lesson on Thinkific to watch the video / view the material.'),
(137, '7.3 Assignment — Write a Task Spec for Manus', 'Open this lesson on Thinkific to watch the video / view the material.'),
(138, '7.4 Mini Quiz — Manus', 'Open this lesson on Thinkific to watch the video / view the material.'),
(139, '8.1 Slides — DeepSeek', 'Open this lesson on Thinkific to watch the video / view the material.'),
(140, '8.2 Video — Build Your First DeepSeek AI Agent (Free)', 'Open this lesson on Thinkific to watch the video / view the material.'),
(141, '8.3 Assignment — Design a Low-Cost Agent', 'Open this lesson on Thinkific to watch the video / view the material.'),
(142, '8.4 Mini Quiz — DeepSeek', 'Open this lesson on Thinkific to watch the video / view the material.'),
(143, '9.1 Slides — Choosing the Right Agent', 'Open this lesson on Thinkific to watch the video / view the material.'),
(144, '9.2 Video — AI Agents vs. LLMs: Choosing the Right Tool', 'Open this lesson on Thinkific to watch the video / view the material.'),
(145, '9.3 Assignment — Make a Choice and Justify It', 'Open this lesson on Thinkific to watch the video / view the material.'),
(146, '9.4 Mini Quiz — Choosing the Right Agent', 'Open this lesson on Thinkific to watch the video / view the material.'),
(147, '▸ Final Knowledge test', 'Course section — open the full section on Thinkific.'),
(148, 'Final Knowledge test', 'Open this lesson on Thinkific to watch the video / view the material.'),
(149, '▸ Final course evaluation', 'Course section — open the full section on Thinkific.'),
(150, 'Course evaluation', 'Open this lesson on Thinkific to watch the video / view the material.')
) as v(ord, title, content);
