-- Rebuild AI in Medicine as 13 modules with typed lessons + video placeholders
alter table public.lessons add column if not exists external_url text;
alter table public.lessons add column if not exists lesson_type text;

-- remove the earlier single-module import
delete from public.modules
 where title = 'AI in Medicine: Practical Applications for Healthcare';

insert into public.modules (title, description, sort_order) values
('(Optional) Module 0: foundation, theory, and Application', 'Section 1 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 1),
('Module 1: AI in Medicine: Basic and general day to day applications', 'Section 2 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 2),
('Module 2: Image & Video Generation, and AI Ethics', 'Section 3 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 3),
('Module 3: AI Teaching & Learning Assistants', 'Section 4 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 4),
('Module 4: AI for Academic Career Development', 'Section 5 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 5),
('Module 5: AI-Enhanced Literature Search', 'Section 6 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 6),
('Module 6: Research Proposal & Methodology', 'Section 7 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 7),
('Module 7: Statistics & Data Analysis', 'Section 8 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 8),
('Module 8: Manuscript Writing & AI Governance', 'Section 9 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 9),
('Module 10: Miscellaneous', 'Section 10 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 10),
('Optional : AI Agentic use', 'Section 11 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 11),
('Final Knowledge test', 'Section 12 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 12),
('Final course evaluation', 'Section 13 of the AI in Medicine: Practical Applications for Healthcare course (cloned from Thinkific).', 13);

insert into public.lessons (module_id, title, content, external_url, video_url, lesson_type, sort_order)
select m.id, v.title, v.content, 'https://nncceducation.thinkific.com/courses/take/ai-placeholder-2', null, v.ltype, v.ord
from (values
(1, 1, 'Data science and machine learning', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(1, 2, 'AI toolkit navigating real time application in healthcare', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(1, 3, 'Applied biostatistics for clinical reasoning how work around our dyscalculia', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(1, 4, 'Holding Hands with the Machine', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(1, 5, 'Welcome to Your new AI staff how to use LLM as your research and administrative assistant', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(1, 6, 'Malpraxis-legal dilemmas and challenges with AI in healthcare By Dr. Abdullah Chahin', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(2, 2, 'Prompt Engineering Basics', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 3, 'Prompt Engineering Handout', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(2, 4, 'ChatGPT', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 5, 'ChatGPT Handout', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(2, 6, 'Grok', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 7, 'Grok Hand out', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(2, 8, 'Gemini', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 9, 'Link for Gemini', 'Reading — open this lesson on Thinkific.', 'text'),
(2, 10, 'Google Gemini Hand out', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(2, 11, 'Claude AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 12, 'Claude AI handout', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(2, 13, 'Module -1 Assignment', 'Reading — open this lesson on Thinkific.', 'text'),
(2, 14, 'How to Submit the Module 1 Assignment - Step by Step Guide', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(2, 15, 'AI Assignment Checker - Module 1', '🗳 Survey — complete it on Thinkific.', 'survey'),
(2, 16, 'Upload Module -1 Assignment Files and Scoresheet here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(3, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(3, 2, 'Privacy and Ethics in AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 3, 'Creating AI-Generated Medical illustrations and Comics', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 4, 'Comic Prompt Generator - Major Upgrade', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 5, 'Links of AI Prompt Generator, Medical Illustrations & Comic Generator GPTs', '🔴 Live session — details on Thinkific.', 'live'),
(3, 6, 'Creating video using AI-1', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 7, 'Creating videos using AI -2', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 8, 'Creating videos using AI agents', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 9, 'Create Scientific Posters with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(3, 10, 'Prompt to convert PDF Article to Scientific Poster in IMRAD', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(3, 11, 'Module -2 Assignments', 'Reading — open this lesson on Thinkific.', 'text'),
(3, 12, 'Upload Module -2 Assignment Files and Certificate here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(4, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(4, 2, '3.1 NotebookLM Basics', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 3, 'NotebookLM update', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 4, '3.2 Adding Sources to NotebookLM', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 5, '3.3 Podcast and Summary Report Generation', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 6, '3.4 Video and Mindmap Generation', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 7, '3.5 Creating Amazing Powerpoints from Textbooks', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 8, '3.6 Infographics Quiz and Flashcards', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 9, '3.7 Claude Artifacts and Gemini Canvas as Learning Companions', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 10, '3.8 CustomGPT and Gemini GEMS as Study Companions', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(4, 11, 'Upload Module 3 assignment here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(4, 12, 'Tutorial on Module 3 Assignment Submission', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(5, 2, '4.1 Blueprint of a Perfect CV', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 3, '4.2 CV Creation with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 4, '4.3 Designing the Visual Layouts of the CV', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 5, '4.4 Reference Letter Etiquettes and AI Disclosures', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 6, '4.5 Creating a stunning LinkedIn Profile from the CV', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 7, '4.6 Creating Portfolio Website from CV with QR Code', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(5, 8, 'Download this Sample CV PDF for Assignment', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(5, 9, 'Module 4 Assignment', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(6, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(6, 2, '5.1 Consensus AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 3, '5.2 Perplexity AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 4, '5.3 Systematic Review planning with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 5, 'Systematic Review Prompts & Links', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(6, 6, '5.4 Elicit AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 7, '5.5 Creating PRISMA Flow diagrams with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 8, 'Research Rabbit', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(6, 9, 'Upload Module 5 assignment here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(7, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(7, 2, '6.1 Brainstorming SMART Objectives', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(7, 3, '6.2 Proposal Writing with ChatGPT and Gemini DeepResearch modes', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(7, 4, '6.3 Proposal Writing with Grok, Perplexity and Consensus AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(7, 5, 'Sample Size Calculation Tool', 'Reading — open this lesson on Thinkific.', 'text'),
(7, 6, '6.4 DAG - Concept and Visualization with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(7, 7, 'DAG Creation Prompt', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(7, 8, 'Upload Module 6 assignment here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(8, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(8, 2, '7.1 Fundamentals Concepts of Descriptive and Inferential Statistics', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(8, 3, '7.2 Julius AI for Data Analysis', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(8, 4, '7.3 Quadratic AI and Gemini CoPilot in Google Sheets', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(8, 5, 'Prompts - AI Data Analysis using Julius', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(8, 6, 'Data Analysis using Claude CoWork', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(8, 7, 'Cowork Prompt Conductor GPT - The Power of Micro-Prompting in Medical Writing', 'Reading — open this lesson on Thinkific.', 'text'),
(8, 8, 'Sample Size Calculation with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(8, 9, 'Sample Prompts for Module 7', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(8, 10, 'Sample Data Files', '⬇ Downloadable file — get it on Thinkific.', 'download'),
(8, 11, 'Upload Module 7 assignment here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(9, 1, 'Module Objectives', 'Reading — open this lesson on Thinkific.', 'text'),
(9, 2, '8.1 Fundamentals of IMRAD Framework', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 3, '8.2 Manuscript Writing with PaperPal in IMRAD format', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 4, 'Coupon Codes for Paperpal', 'Reading — open this lesson on Thinkific.', 'text'),
(9, 5, 'How to Add Custom Articles to Paperpal', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 6, '8.3 Zotero and its integration with AI tools', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 7, '8.4 Plagiarism Detection tools and Paraphrasing with AI', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 8, '8.5 AI Detection and Guidelines in Research', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 9, 'AI watermark removal prompt', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(9, 10, 'AI Humanisers - Which is the best one in 2026', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(9, 11, 'Upload Module 8 assignment here', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(10, 1, 'How to create AI tools using a combo of Gemini and Google AI studio', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(10, 2, 'Bulid your first AI app in AI studio', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(10, 3, 'A step-by-step guide', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(10, 4, 'A step by step infographic', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(10, 5, 'Cloning your voice and adding it to PPT', '🎬 Video — the recording will be uploaded here. For now, watch it on Thinkific.', 'video'),
(11, 1, '1.1 Slides — Course Objectives & Orientation', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 2, '1.2 Video — AI Agents, Clearly Explained', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 3, '1.3 Assignment — Set Your Learning Goal', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 4, '1.4 Mini Quiz — Objectives & Orientation', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 5, '2.1 Slides — Agentic AI in 2026: The Shared Picture', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 6, '2.2 Video — Agentic AI Frameworks Explained', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 7, '2.3 Assignment — Apply the Verifiability Lens', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 8, '2.4 Mini Quiz — The Shared Picture', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 9, '3.1 Slides — How to Drive Any Agent Well', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 10, '3.2 Video — How to Use Agentic AI (Prompting in Action)', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 11, '3.3 Assignment — Rewrite a Weak Prompt', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 12, '3.4 Mini Quiz — Driving Agents Well', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 13, '4.1 Slides — Claude (Anthropic)', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 14, '4.2 Video — Master Claude in 20 Minutes (Beginner Guide)', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 15, '4.3 Assignment — Plan a Claude Task', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 16, '4.4 Mini Quiz — Claude', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 17, '5.1 Slides — Gemini (Google)', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 18, '5.2 Video — Master Gemini: Workspace, Deep Research & Gems', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 19, '5.3 Assignment — Use the Large Context Window', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 20, '5.4 Mini Quiz — Gemini', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 21, '6.1 Slides — Microsoft Copilot', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 22, '6.2 Video — Build and Use Agents in Microsoft 365 Copilot', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 23, '6.3 Assignment — Match the Surface to the Task', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 24, '6.4 Mini Quiz — Microsoft Copilot', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 25, '7.1 Slides — Manus', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 26, '7.2 Video — Manus AI Explained: Setup & Use Cases', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 27, '7.3 Assignment — Write a Task Spec for Manus', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 28, '7.4 Mini Quiz — Manus', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 29, '8.1 Slides — DeepSeek', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 30, '8.2 Video — Build Your First DeepSeek AI Agent (Free)', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 31, '8.3 Assignment — Design a Low-Cost Agent', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 32, '8.4 Mini Quiz — DeepSeek', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(11, 33, '9.1 Slides — Choosing the Right Agent', '📄 PDF / handout — open or download it on Thinkific.', 'pdf'),
(11, 34, '9.2 Video — AI Agents vs. LLMs: Choosing the Right Tool', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(11, 35, '9.3 Assignment — Make a Choice and Justify It', '📝 Assignment — submit it on Thinkific.', 'assignment'),
(11, 36, '9.4 Mini Quiz — Choosing the Right Agent', '❓ Quiz — complete it on Thinkific.', 'quiz'),
(12, 1, 'Final Knowledge test', '🧩 Interactive content — open it on Thinkific.', 'multimedia'),
(13, 1, 'Course evaluation', '🧩 Interactive content — open it on Thinkific.', 'multimedia')
) as v(chsort, ord, title, content, ltype)
join public.modules m on m.sort_order = v.chsort;
